// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfR8fMUZKarHK18nO7jxZSC32UNSUtPPU',
    appId: '1:899429261983:web:ce65957cd9c4a64a7a78aa',
    messagingSenderId: '899429261983',
    projectId: 'rental-assignment',
    authDomain: 'rental-assignment.firebaseapp.com',
    storageBucket: 'rental-assignment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgGR18efnZWb381y9mnXnPpR0atFXI04',
    appId: '1:899429261983:android:079eca0cdec61dbf7a78aa',
    messagingSenderId: '899429261983',
    projectId: 'rental-assignment',
    storageBucket: 'rental-assignment.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfR8fMUZKarHK18nO7jxZSC32UNSUtPPU',
    appId: '1:899429261983:web:f8f08e04bdb77b407a78aa',
    messagingSenderId: '899429261983',
    projectId: 'rental-assignment',
    authDomain: 'rental-assignment.firebaseapp.com',
    storageBucket: 'rental-assignment.firebasestorage.app',
  );
}
